### ISSUE TITLE
Implement recommended gas price

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#10]
https://docs.google.com/presentation/d/1hCt72FKBthEtCTWRQvjfvjctbJz3MLHIooE7rP20eZA/edit?pli=1#slide=id.g282ed5981d5_0_117

TODO: Update the issue description to what exactly needs to be done (the above is a private presentation).

**Comment by bbenligiray** [comment]
See [thread](https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1696588971545399)
