### ISSUE TITLE
Investigate why Renovate isn't working and fix

### ISSUE THREAD

**Issue by aquarat** [api3dao/airseeker-v2#106]
See Slack thread [here](https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1700566561191559).

Renovate doesn't appear to be working in this repository. The failure may relate to the config in this PR: https://github.com/api3dao/airseeker-v2/pull/4/files

**Comment by Siegrift** [comment]
It needed to be enabled on this repository. It works now. Thanks to @aquarat 🙏
