### ISSUE TITLE
Add optional chain-specific "fallbackGasLimit" field

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#107]
Add optional `fallbackGasLimit` field similar to https://docs.api3.org/reference/airnode/latest/deployment-files/config-json.html#options-fulfillmentgaslimit as fallback instead of hardcoded 2_000_000 during gas limit estimation. If the fallback is not defined and the provider gas limit estimation fails, make the gas estimation error out (and avoid update).

**Comment by bbenligiray** [comment]
I guess it should be called something like `fallbackGasLimit`

**Comment by Siegrift** [comment]
Yeah, that's more accurate.
