### ISSUE TITLE
Add Loki integration to CloudFormation template

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#111]
Similarly to https://github.com/api3dao/signed-api/pull/129

**Comment by bbenligiray** [comment]
I created a Grafana Cloud account and invited you to it

**Comment by bbenligiray** [comment]
FYI @bdrhn9 also has a CF template in airseeker-admin and it already has Loki integration

**Comment by Siegrift** [comment]
Is it based on the one in the repo? Any reason, why not create a PR here? 

There is a question whether we need to have the CF template in this repo when the airseeker-admin will hold it's own. I'd still argue that it should be located here and in airseeker-admin, you should have the template that is deployed at the current time.

**Comment by bbenligiray** [comment]
I mean you can use it as reference

**Comment by bdrhn9** [comment]
> Is it based on the one in the repo? Any reason, why not create a PR here?
> 
> There is a question whether we need to have the CF template in this repo when the airseeker-admin will hold it's own. I'd still argue that it should be located here and in airseeker-admin, you should have the template that is deployed at the current time.

In my view, the version stored in this repository should not include Loki integration. Given that the repository is public, individuals looking to swiftly deploy Airseeker can utilize this CloudFormation template instead of setting up a Grafana Cloud account or having to remove Loki integration.

**Comment by Siegrift** [comment]
That's also a way to look at it, but the downside is that whenever the CF template changes in this repo and you'll want to update it in airseeker-admin, you will need to re-apply the Loki changes there (which can be error prone). In the short term, we are the only ones running the Airseeker so we should prioritise ourselves and might just have the Loki one here. Alternatively, we can maintain both CF templates with/without Loki.

> I mean you can use it as reference

I don't have access to the repo (not sure if you want me to have), but feel free to share me the CF file (it'll save me some time).

**Comment by bbenligiray** [comment]
I gave access, it will go under the monorepo anyway https://github.com/api3dao/airseeker-admin/blob/main/src/cfn-template.ts

**Comment by Siegrift** [comment]
After doing a few more changes for Signed API deployments I think this is no longer necessary. The source of truth (what is deployed) is in the deployments repo (e.g. airseeker-admin). Such CloudFormation will also have alerts, which is not something you need to setup for a simple deployment.

So I'd close this issue and let the cloudformation template here serve as minimal example of what's necessary to deploy the service on the Cloud. Feel free to re-open if you disagree.
