### ISSUE TITLE
Configure alerts

### ISSUE THREAD

**Issue by vponline** [api3dao/airseeker-v2#13]
Configure alerts based on logs.

This task to be done after #8.

**Comment by Siegrift** [comment]
Does this belong in this repo? The alerts are probably going to be some separate service.

**Comment by vponline** [comment]
It depends, the alert options that were discussed in the beginning were either OpsGenie alerts sent from the airseeker directly, or alternatively some solution to generate alerts based on the exported logs.

**Comment by Siegrift** [comment]
I see. I think this is blocked until we make a decision what alerting mechanism we want to have in place.

Before that I think we should focus on the implementation and logs. (I'd say we can get pretty far with just good enough logs).

**Comment by Siegrift** [comment]
We have agreed on call that logs might be enough. I'm closing this and we can recreate/reopen if this becomes relevant in the future.
