### ISSUE TITLE
Create an Airseeker V2 flowchart

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/airseeker-v2#27]
There are supposed to be three loops:
1. Periodically fetches the signed API URLs
2. Periodically fetches signed data from the signed APIs
3. Periodically updates on-chain values in batches in a staggered way

**Comment by bbenligiray** [comment]
@aquarat will add it to the signed api repo

**Comment by Siegrift** [comment]
> will add it to the signed api repo

You meant this (airseeker-v2) repo, right?
