### ISSUE TITLE
Support running Airseeker locally

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#63]
The signed API module contains an [e2e module](https://github.com/api3dao/signed-api/blob/main/packages/e2e/README.md) that offers running pusher and signed API together.

We should do something similar for Airseeker just to see whether all of these services work correctly with each other.

**Comment by BTT21000** [comment]
It'd be good to document this with a comprehensive README.md as per what was done for the signed API [e2e module](https://github.com/api3dao/signed-api/blob/main/packages/e2e/README.md)
