### ISSUE TITLE
Only store fresh signed data

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#79]
Currently, we do not store active dAPIs in state which means that we need to store the signed data for every beacon even if there are only a few active beacons among the active dAPIs.

Another side effect of this is that once we fetch a data for a beacon, we persist it forever.

**Comment by aquarat** [comment]
We store dapiNames received from the contract in the state, so the signed data fetch loop can just filter incoming samples by active dAPIs. I'll do this.

**Comment by Siegrift** [comment]
I remember we discussed the first part (only saving data for active dAPIs) in the spec and @bbenligiray wasn't sold on this. 

> Another side effect of this is that once we fetch a data for a beacon, we persist it forever.

We didn't discuss this which feels to me is a reason of itself to implement this. We should discuss this at the weekly call.

>  I'll do this.

Yeah, go ahead.

**Comment by aquarat** [comment]
It was decided in the call to (1) not store active dapis in the state and (2) purge the signed data store by timestamp (> 24 hours) and not by active dapis.

**Comment by Siegrift** [comment]
Can you change the issue title as well?
