### ISSUE TITLE
Import deployed AirseekerRegistry (old DapiDataRegistry) addresses

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#82]
Api3ServerV1 address is optional in Airseeker because and we fallback to the deployed address taken from api3-protocol-v1 repo. We should do the same for DapiDataRegistry once the contract is deployed.

**Comment by bbenligiray** [comment]
As a note, arguably, the Api3ServerV1 deployment should live in the dapi-management repo as it's not a pure protocol contract

**Comment by bbenligiray** [comment]
AirseekerRegistry is not a protocol contract / it's user specific so it shouldn't be auto-imported (and it's not exported in the first place for this reason)

**Comment by Siegrift** [comment]
Ok, in that case I think the issue can be closed.
