### ISSUE TITLE
Come up with strategy around multicall batch sizes

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#85]
Batch sizes are likely going to be different per provider as they can apply their own limits. We need to set the limit for multicalling active dAPIs.

See [this thread](https://api3workspace.slack.com/archives/C05TQPT7PNJ/p1699529274108669) for reference.

**Comment by bbenligiray** [comment]
A similar concern is eth_getLogs limits and providers used in an Airnode config. We just set a blanket limit for the chain there and weed out the providers that don't work with it.

**Comment by aquarat** [comment]
Could we maybe do a quick benchmark when Airseeker starts?

**Comment by aquarat** [comment]
It was decided to hardcode batch sizes to 10.
