### ISSUE TITLE
Implement using setSponsorLastUpdateTimestampMs after a transaction is submitted

### ISSUE THREAD

**Issue by vponline** [api3dao/airseeker-v2#94]
Apply the `setSponsorLastUpdateTimestampMs` function after a tranasction is submitted. This should be done only the first time that a particular update is submitted, and not overwritten for scaling pending transactions.

**Comment by Siegrift** [comment]
Isn't this done by https://github.com/api3dao/airseeker-v2/pull/88/commits/3a2c8558534cf2a2e16af21f58931cd7f4cfb5c8 ?

**Comment by vponline** [comment]
Yeah, I missed that you already included it in the PR. I thought I had deleted this issue already 😅
