### ISSUE TITLE
Investigate CI e2e test issue

### ISSUE THREAD

**Issue by Siegrift** [api3dao/airseeker-v2#96]
See: https://github.com/api3dao/airseeker-v2/actions/runs/6863104836/job/18662177317

But it has happened a few times as well. Re-running doesn't help (at least from my attempts) but amend + force-pushing does. I was not able to reproduce it locally, nor find any relevant information.

We may also remove/merge/update the test if this keeps happening and we are unable to find the reason.

**Comment by aquarat** [comment]
Interesting, the error message can be reproduced by killing Hardhat while the test is running.

**Comment by vponline** [comment]
I saw this today: https://github.com/NomicFoundation/hardhat/issues/4601
